### PR TITLE
Add environment variable expansion to options

### PR DESCRIPTION
**Pull request by piepie62**
Allows using environment variables for e.g. centralized library folders that other collaborators may have in different paths

### CODE REVIEW

**Comment by joshtynjala** [comment]
As far as I can tell, TypeScript's _tsconfig.json_ file format does not support environment variables in paths. While the two file formats are not exactly the same in every way, I would prefer not to diverge from that behavior.

**Comment by piepie62** [comment]
Fair enough. What would you suggest as the best solution for the problem this was supposed to solve? I'd be willing to implement something else that ended up with this same functionality; a config option for a folder where SWCs are also searched for, perhaps?

**Comment by joshtynjala** [comment]
AS3 compilers actually support something called tokens, which involve the same syntax that I think you were trying to use here for environment variables. There are some built-in compiler tokens, like `flexlib` for Flex and `royalelib` for Royale, which point to the _frameworks_ directory in the SDK. It's useful for `source-path` or `library-path`, for instance.

Here's an example using `${royalelib}` in a Royale project:

```json
"js-library-path": [
	"${royalelib}/js/libs/MXRoyaleBaseJS.swc",
	"${royalelib}/js/libs/MXRoyaleJS.swc"
]
```

However, on the command line for mxmlc/compc, you can also define custom tokens using the `+` prefix (instead of `-` used by compiler options). So something like this is possible:

```sh
mxmlc +mytoken -source-path+=${mytoken}/file.swc
```

It might be interesting to add a way for asconfigc to also accept tokens on its command line, and then it could pass them on to mxmlc/compc when it launches them to compile. From there, vscode-as3mxml could include some sort of way to define custom AS3 compiler tokens for a project, such as in _settings.json_.

**Comment by piepie62** [comment]
Okay, that sounds like a reasonable fix. I'll look into making that work.

**Pull request closed without merging**
